name: Run Stock Script

on:
  schedule:
    - cron: '0 * * * *'  # 毎時0分に実行（UTC時間）

jobs:
  run-stock-script:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Python をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 必要なパッケージをインストール
        run: pip install yfinance pandas openpyxl

      - name: 株価取得スクリプトを実行
        run: python get_stock_data.py

      - name: Excelファイルをアップロード
        uses: actions/upload-artifact@v3
        with:
          name: stock-data
          path: output/*.xlsx

