name: Run Stock Script

on:
  workflow_dispatch:  # 手動実行も可能
  schedule:           # 毎時0分に自動実行（UTC基準）
    - cron: '0 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: 必要なPythonパッケージをインストール
        run: |
          pip3 install yfinance pandas openpyxl

      - name: 株価取得スクリプトを実行
        run: python3 get_stock_data.py

      - name: Excelファイルをアップロード
        uses: actions/upload-artifact@v4
        with:
          name: stock-data
          path: output/*.xlsx
