name: Run Stock Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:  # ← ここが1回だけ必要
  run-stock-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install packages
        run: pip install yfinance pandas openpyxl

      - name: Run script
        run: python get_stock_data.py

      - name: Upload Excel
        uses: actions/upload-artifact@v3
        with:
          name: stock-data
          path: output/*.xlsx
